#ifndef HAUNT_RENDERER_OPENGL_H
#define HAUNT_RENDERER_OPENGL_H

#define GL_DEBUG_ENABLED 1
#define VSYNC_ENABLED 1
#define SRGB_ENABLED 1
#define MSAA_ENABLED 1

void gl_init(void);

#endif // HAUNT_RENDERER_OPENGL_H
